### ISSUE TITLE
是不是有请求频率限制

### ISSUE THREAD

**Issue by caiyaonan** [ReaJason/xhs#14]
获取笔记数据时，获取几十条就会出现频率限制
`
Traceback (most recent call last):
  File "/home/python3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/www/wwwroot/xhs_python/app.py", line 27, in xhs
    client = XhsClient(cookie)
  File "/home/python3.9/lib/python3.9/site-packages/xhs/core.py", line 114, in __init__
    self.cookie = cookie
  File "/home/python3.9/lib/python3.9/site-packages/xhs/core.py", line 124, in cookie
    self.activate()
  File "/home/python3.9/lib/python3.9/site-packages/xhs/core.py", line 568, in activate
    return self.post(uri, data={})
  File "/home/python3.9/lib/python3.9/site-packages/xhs/core.py", line 171, in post
    return self.request(method="POST", url=f"{self._host}{uri}",
  File "/home/python3.9/lib/python3.9/site-packages/xhs/core.py", line 156, in request
    raise IPBlockError(self.IP_ERROR_STR)
xhs.exception.IPBlockError: 网络连接异常，请检查网络设置或重启试试
`

**Comment by ReaJason** [comment]
是的，我测试的好像是固定次数后会被封掉 IP 的亚子，每个接口不一样

**Comment by ReaJason** [comment]
> > 快代理的隧道代理
> 
> 但是，使用代理的话，我们的cookie 有可能因为频繁切换ip 导致封号吧

不清楚，没测试，这个网络异常可以通过等待三到六分钟解决

**Comment by fengzhengkeji** [comment]
> 

大佬现在弄出来了吗，我也是刚才就提示：浏览器异常，请尝试关闭/卸载风险插件或重启试试！

**Comment by fengzhengkeji** [comment]
> > > 
> > 
> > 
> > 大佬现在弄出来了吗，我也是刚才就提示：浏览器异常，请尝试关闭/卸载风险插件或重启试试！
> 
> 你有没有用代理ip，我今天用的快代理后才会的

不是代理的问题，这几个接口X-s参数算法更新了，不知道作者有没有群，我觉得可以建个群讨论，以后肯定还会遇见这样的问题

**Comment by ReaJason** [comment]
> 不是代理的问题，这几个接口X-s参数算法更新了，不知道作者有没有群，我觉得可以建个群讨论，以后肯定还会遇见这样的问题

Q群：668689006

**Comment by glorysaladin** [comment]
> > 不是代理的问题，这几个接口X-s参数算法更新了，不知道作者有没有群，我觉得可以建个群讨论，以后肯定还会遇见这样的问题
> 
> Q群：668689006

这个群是不是没了，搜不到

**Comment by ReaJason** [comment]
是的，精力有限解散了
