### ISSUE TITLE
浏览器异常，请尝试关闭/卸载风险插件或重启试试！

### ISSUE THREAD

**Issue by Robin-HUST** [ReaJason/xhs#19]
from xhs import XhsClient

cookie = "mycookie"
xhs_client = XhsClient(cookie, user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36")
xhs_client.save_files_from_note_id("64467ef40000000013012007",
                                    r"C:\Users\COMPUTER\Desktop\bot")

Traceback (most recent call last):
  File "c:\Users\COMPUTER\Desktop\bot\tempCodeRunnerFile.python", line 4, in <module>
    xhs_client = XhsClient(cookie, user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36")
  File "C:\Users\COMPUTER\AppData\Local\Programs\Python\Python310\lib\site-packages\xhs\core.py", line 116, in __init__
    self.cookie = cookie
  File "C:\Users\COMPUTER\AppData\Local\Programs\Python\Python310\lib\site-packages\xhs\core.py", line 126, in cookie
    self.activate()
  File "C:\Users\COMPUTER\AppData\Local\Programs\Python\Python310\lib\site-packages\xhs\core.py", line 573, in activate
    return self.post(uri, data={})
  File "C:\Users\COMPUTER\AppData\Local\Programs\Python\Python310\lib\site-packages\xhs\core.py", line 176, in post
    return self.request(method="POST", url=f"{self._host}{uri}",
  File "C:\Users\COMPUTER\AppData\Local\Programs\Python\Python310\lib\site-packages\xhs\core.py", line 163, in request
    raise DataFetchError(data.get("msg", None))
xhs.exception.DataFetchError: 浏览器异常，请尝试关闭/卸载风险插件或重启试试！

**Comment by DarkSanys** [comment]
解决了吗？

**Comment by Cyiming** [comment]
一样

**Comment by ReaJason** [comment]
这个问题的出现原因是因为 X-s 签名算法更新了，目前还无法找到好的解决办法，不好意思，#13

**Comment by DarkSanys** [comment]
这个问题的出现原因是因为 X-s 签名算法更新了，相信老大ReaJason一定可以解决的，再等等吧。

**Comment by ReaJason** [comment]
> 这个问题的出现原因是因为 X-s 签名算法更新了，相信老大ReaJason一定可以解决的，再等等吧。

解决了🥳
