### ISSUE TITLE
请问一下这是什么问题导致的？

### ISSUE THREAD

**Issue by haobosang** [ReaJason/xhs#33]
Traceback (most recent call last):
  File "/home/one/myhome/path/to/xhs/test.py", line 61, in <module>
    a=xhs_client.get_user_all_notes(value)
  File "/home/one/.local/lib/python3.10/site-packages/xhs/core.py", line 411, in get_user_all_notes
    note = self.get_note_by_id(note_id)
  File "/home/one/.local/lib/python3.10/site-packages/xhs/core.py", line 190, in get_note_by_id
    res = self.post(uri, data)
  File "/home/one/.local/lib/python3.10/site-packages/xhs/core.py", line 178, in post
    return self.request(method="POST", url=f"{self._host}{uri}",
  File "/home/one/.local/lib/python3.10/site-packages/xhs/core.py", line 165, in request
    raise DataFetchError(data.get("msg", data))
xhs.exception.DataFetchError: 当前内容无法展示

**Comment by ReaJason** [comment]
可能爬的时候，用户做了隐藏笔记的操作，导致你这边笔记爬详情的时候失败了

**Comment by ReaJason** [comment]
可能爬的时候，用户做了隐藏笔记的操作，导致你这边笔记爬详情的时候失败了

**Comment by ReaJason** [comment]
麻烦提供一下 user_id，我尝试复现一下

**Comment by haobosang** [comment]
@ReaJason 这个576e7b1d50c4b4045222de08
