### ISSUE TITLE
该脚本发笔记，会被小红书判定限流吗？

### ISSUE THREAD

**Issue by godJBJ** [ReaJason/xhs#38]
如题

**Comment by godJBJ** [comment]
只能发笔记试试看流量正不正常了。

**Comment by godJBJ** [comment]
发布笔记有时候也会报错（测试有一定概率报错），如下：
Traceback (most recent call last):
  File "D:\project\xhs-master\example\basic_usage.py", line 54, in <module>
    note_info = xhs_client.create_image_note(title, desc, images, is_private=False, post_time="2023-08-03 16:06:00")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\xhs-master\xhs\core.py", line 783, in create_image_note
    return self.create_note(title, desc, NoteType.NORMAL.value, ats=ats, topics=topics,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\xhs-master\xhs\core.py", line 743, in create_note
    return self.post(uri, data, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\xhs-master\xhs\core.py", line 187, in post
    self._pre_headers(uri, data, is_creator=is_creator)
  File "D:\project\xhs-master\xhs\core.py", line 155, in _pre_headers
    self.sign(
  File "D:\project\xhs-master\example\basic_usage.py", line 29, in sign
    encrypt_params = context_page.evaluate("([url, data]) => window._webmsxyw(url, data)", [uri, data])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\xhs-master\venv\Lib\site-packages\playwright\sync_api\_generated.py", line 8698, in evaluate
    self._sync(
  File "D:\project\xhs-master\venv\Lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "D:\project\xhs-master\venv\Lib\site-packages\playwright\_impl\_page.py", line 395, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\xhs-master\venv\Lib\site-packages\playwright\_impl\_frame.py", line 277, in evaluate
    await self._channel.send(
  File "D:\project\xhs-master\venv\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\xhs-master\venv\Lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "D:\project\xhs-master\venv\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Execution context was destroyed, most likely because of a navigation

Process finished with exit code 1
作者大大碰到过这种情况吗？对python不是很熟看不太懂...

**Comment by ReaJason** [comment]
暂时不太懂 playwright 为什么会报这个错误，可以试试捕获异常然后重试。
