### ISSUE TITLE
xhs.exception.DataFetchError: {'code': -1, 'success': False}

### ISSUE THREAD

**Issue by youyoupyn** [ReaJason/xhs#58]
(python) yanandeMacBook-Pro:example $ python3 basic_sign_usage.py
Traceback (most recent call last):
  File "/Users/yananpan/python/xhs-master/example/basic_sign_usage.py", line 21, in <module>
    note_info = xhs_client.get_note_by_id("63db8819000000001a01ead1")
  File "/Users/yananpan/python/lib/python3.9/site-packages/xhs/core.py", line 201, in get_note_by_id
    res = self.post(uri, data)
  File "/Users/yananpan/python/lib/python3.9/site-packages/xhs/core.py", line 189, in post
    return self.request(
  File "/Users/yananpan/python/lib/python3.9/site-packages/xhs/core.py", line 177, in request
    raise DataFetchError(data)
xhs.exception.DataFetchError: {'code': -1, 'success': False}

**Comment by youyoupyn** [comment]
请求接口返回： {'code': -1, 'success': False}，应该是x-s验证没有通过，不知道什么原因，我打印header信息，里面缺少x-s-common　这个值

**Comment by ReaJason** [comment]
更新了一下 base_server 用例，麻烦用最新的

**Comment by youyoupyn** [comment]
更新后，已经好了，多谢
