### ISSUE TITLE
请求结果报错：xhs.exception.DataFetchError: {'code': -1, 'success': False}

### ISSUE THREAD

**Issue by youyoupyn** [ReaJason/xhs#65]
<img width="1336" alt="image" src="https://github.com/ReaJason/xhs/assets/137590054/90e332d1-5d11-4f80-be66-b376ccdfe36d">

请求case错误如下：应该是签名验证没有通过
(python3) [root@VM-8-17-centos xhs]# python usage.py 
Traceback (most recent call last):
  File "/www/python3/xhs/usage.py", line 24, in <module>
    note_info = xhs_client.get_note_by_id("63db8819000000001a01ead1")
  File "/www/python3/lib/python3.9/site-packages/xhs/core.py", line 199, in get_note_by_id
    res = self.post(uri, data)
  File "/www/python3/lib/python3.9/site-packages/xhs/core.py", line 187, in post
    return self.request(
  File "/www/python3/lib/python3.9/site-packages/xhs/core.py", line 175, in request
    raise DataFetchError(data)
xhs.exception.DataFetchError: {'code': -1, 'success': False}

**Comment by youyoupyn** [comment]
我对x-s, x-t 做了输出，可以正常请求到，但是小红书那边返回{'code': -1, 'success': False}

**Comment by ReaJason** [comment]
不太清楚，签名错误就是环境问题，这个环境有点严苛，你服务器跑的话建议 docker 了，docker 试了能正常运行
