### ISSUE TITLE
请问只能在本机上运行吗，云服务器可以运行吗

### ISSUE THREAD

**Issue by glorysaladin** [ReaJason/xhs#90]
我再腾讯云服务器上运行程序一直报如下错误信息，在本机运行上正常。 

2024-03-19 20:20:07.684035
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 12813 is closed
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 12979 is closed
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 13063 is closed
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 13309 is closed
Traceback (most recent call last):
  File "basic_usage.py", line 50, in <module>
    note = xhs_client.get_note_by_id("65f106f30000000014004202")
  File "/usr/local/python3/lib/python3.8/site-packages/xhs/core.py", line 200, in get_note_by_id
    res = self.post(uri, data)
  File "/usr/local/python3/lib/python3.8/site-packages/xhs/core.py", line 185, in post
    self._pre_headers(uri, data, is_creator=is_creator)
  File "/usr/local/python3/lib/python3.8/site-packages/xhs/core.py", line 149, in _pre_headers
    self.external_sign(
  File "basic_usage.py", line 38, in sign
    raise Exception("重试了这么多次还是无法签名成功，寄寄寄")
Exception: 重试了这么多次还是无法签名成功，寄寄寄

**Comment by MrHe007** [comment]
我在mac上运行失败了
