### ISSUE TITLE
视频发布有文件大小限制吗？

### ISSUE THREAD

**Issue by SarcomTDG** [ReaJason/xhs#98]
报错内容
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/xhs_uploade/./api/app.py", line 33, in handle_upload_videos
    result =upload_videos(cookies, title,videoPathUrl,coverPath,publishDatetimes,tags)
  File "/xhs_uploade/api/upload_video_to_xhs_api.py", line 78, in upload_videos
    note = xhs_client.create_video_note(
  File "/usr/local/lib/python3.10/site-packages/xhs/core.py", line 940, in create_video_note
    res = self.upload_file(
  File "/usr/local/lib/python3.10/site-packages/xhs/core.py", line 767, in upload_file
    raise Exception("video too large, < 5M")

**Comment by ReaJason** [comment]
5M 限制，因为超过 5M 用的分片上传我还没调通（不过有一点时间没调了）

**Comment by HeartDawnWY** [comment]
@ReaJason 
5M限制问题 有其他办法实现吗？
